#!/bin/bash
set -xeu

source cf-pipeline/lib/shared-functions

function main() {
  az login --service-principal -u ${BBL_AZURE_CLIENT_ID} -p ${BBL_AZURE_CLIENT_SECRET} --tenant ${BBL_AZURE_TENANT_ID}
  az group delete -n ${DNS_ZONE_RESOURCE_GROUP}
}

main
