#!/bin/bash -eux

# This is a function used to change a filed in json
# The first parameter is json seletion in jq
# The second parameter is the value to be changed 
# The third parameter is json file
function change_json_field() {
  set +x
  touch tmpFile
  jq "${1}=${2}" ${3} > tmpFile
  mv tmpFile ${3}
  set -x
}

function retryop() {
  set +e
  retry=0
  max_retries=180
  interval=60
  while [ ${retry} -lt ${max_retries} ]; do
    echo "Operation: $1, Retry #${retry}"
    eval $1
    if [ $? -eq 0 ]; then
      echo "Successful"
      break
    else
      let retry=retry+1
      echo "Sleep ${interval} seconds, then retry..."
      sleep ${interval}
    fi
  done
  if [ ${retry} -eq ${max_retries} ]; then
    echo "Operation failed: $1"
    exit 1
  fi
  set -e
}
