---
platform: linux

resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource
    tag: {{docker-tag}}

resources:
- name: cf-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/CloudFoundryOnAzure/cf-pipeline.git
- name: integration-configs
  type: git
  source:
    branch: {{CONFIG_BRANCH}}
    uri: {{CONFIG_REPO_URI}}
    private_key: {{CONFIG_PRIVATE_KEY}}
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
- name: azure-quickstart-templates
  type: git
  source:
    branch: {{AZURE_TEMPLATE_BRANCH}}
    uri: {{AZURE_TEMPLATE_REPO_URI}}
    private_key: {{AZURE_TEMPLATE_PRIVATE_KEY}}
- name: upstream-azure-quickstart-templates
  type: git
  source:
    branch: master
    uri: https://github.com/Azure/azure-quickstart-templates.git
- name: send-an-email
  type: email
  source:
    smtp:
      host: {{smtp-host}}
      port: {{smtp-port}}
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: {{email-from}}
    to: [ {{email-to}} ]  
- name: timer
  type: time
  source: {interval: 168h}

jobs:
- name: check-new-version
  plan:
  - aggregate:
    - {get: timer, trigger: true}
    - {get: upstream-azure-quickstart-templates, params: {submodules: none} }
    - {get: azure-quickstart-templates, params: {submodules: none} }
    - {get: cf-pipeline}
  - task: check-new-version
    file: cf-pipeline/lib/check-new-version/task.yml
    input_mapping: 
      azure-quickstart-templates: upstream-azure-quickstart-templates
    params:
      GIT_COMMIT_USERNAME: {{GIT_COMMIT_USERNAME}}
      GIT_COMMIT_EMAIL: {{GIT_COMMIT_EMAIL}}
  - put: azure-quickstart-templates
    params: {repository: updated-azure-quickstart-templates, force: true, tag: updated-azure-quickstart-templates/tag.log}
    get_params: {submodules: none} 
- name: deploy-cf
  plan:
  - aggregate:
    - {get: cf-pipeline}
    - {get: azure-quickstart-templates, trigger: true, passed: [check-new-version], params: {submodules: none} }
    - {get: integration-configs}
  - task: deploy-cf
    file: cf-pipeline/lib/deploy-cf/task.yml
    params:
      TENANT_ID: {{TENANT_ID}}
      CLIENT_ID: {{CLIENT_ID}}
      CLIENT_SECRET: {{CLIENT_SECRET}}
      RESOURCE_GROUP_NAME: {{RESOURCE_GROUP_NAME}}
      AZURE_REGION: {{AZURE_REGION}}
      SSH_PUBLIC_KEY: {{SSH_PUBLIC_KEY}}
      SSH_PRIVATE_KEY: {{SSH_PRIVATE_KEY}}
      GIT_COMMIT_USERNAME: {{GIT_COMMIT_USERNAME}}
      GIT_COMMIT_EMAIL: {{GIT_COMMIT_EMAIL}}
    input_mapping:
      private-key: integration-configs
      template: azure-quickstart-templates
  - put: integration-configs
    params: {repository: updated-integration-configs, rebase: true, force: true}
- name: login-cf
  plan:
  - aggregate:
    - {get: cf-pipeline}
    - {get: integration-configs, trigger: true, passed: [deploy-cf]}
  - task: login-cf
    file: cf-pipeline/lib/login-cf/task.yml 

- name: sleep
  plan:
  - aggregate:
    - {get: integration-configs, trigger: true, passed: [login-cf]}  
    - {get: cf-pipeline}
  - task: sleep
    file: cf-pipeline/lib/sleep/task.yml
    params:
      SLEEP_TIME: 600

- name: run-cats
  plan:
  - aggregate:
    - {get: cf-deployment-concourse-tasks}
    - {get: integration-configs, trigger: true, passed: [sleep]}
    - {get: cf-acceptance-tests}
    - {get: cf-pipeline}
  - task: run-cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      integration-config: integration-configs
    params:
      CONFIG_FILE_PATH: {{CONFIG_FILE_PATH}}
      NODES: 2
    on_failure:
      task: send-email
      file: cf-pipeline/lib/send-email/task.yml
      params:
        SUBJECT: {{CATS_FAILURE_SUBJECT}}
        BODY: {{CATS_FAILURE_BODY}}
        OUTPUT_SUBJECT_FILE_NAME: email-subject
        OUTPUT_BODY_FILE_NAME: email-body
      on_success:
        put: send-an-email
        params:
          subject: email-out/email-subject
          body: email-out/email-body
 
- name: delete-resource-group
  plan:
  - aggregate:
    - {get: cf-pipeline}
    - {get: integration-configs, trigger: true, passed: [run-cats]}
  - task: delete-resource-group
    file: cf-pipeline/lib/delete-resource-group/task.yml
    params:
      TENANT_ID: {{TENANT_ID}}
      CLIENT_ID: {{CLIENT_ID}}
      CLIENT_SECRET: {{CLIENT_SECRET}}
      RESOURCE_GROUP_NAME: {{RESOURCE_GROUP_NAME}}
    on_success:
      task: send-email
      file: cf-pipeline/lib/send-email/task.yml
      params:
        SUBJECT: {{SUCCESS_SUBJECT}}
        BODY: {{SUCCESS_BODY}}
        OUTPUT_SUBJECT_FILE_NAME: email-subject
        OUTPUT_BODY_FILE_NAME: email-body
      on_success:
        put: send-an-email
        params:
          subject: email-out/email-subject
          body: email-out/email-body
